### PR TITLE
fix imports, code cleaning

### PR DESCRIPTION
**Pull request by azazellochg**
I started to fix imports, moving constants to one file and formatting the code. I also think we should deprecate relion1.X version support. What do you think?
Also, removed most xmipp dependencies. The only direct xmipp call left (except tests) is in postprocess viewer

I am still testing the PR, and more fixes are expected to come. Do not merge yet! :)

### CODE REVIEW

**Comment by dmaluenda** [comment]
I think that localRec from Opic needs Relion 1.4.

Thanks Gregory!

**Comment by azazellochg** [comment]
@dmaluenda yes, I was thinking to keep 1.4 on download servers and use it for opic protocols (till the code is ported to 2.x/3.x), but all relion protocols won't use it. We need to move forward to relion 3 and Sjors has already dropped all support for 1.x :)

**Comment by dmaluenda** [comment]
Nice! I thought in something like that. Agree with relion use 2.X and 3.0 whereas the binaries of relion-1.4 are only for opic. :)

**Comment by josuegbl** [comment]
@azazellochg and @dmaluenda, since scipion 1.2, relion 1.x doesn't support. Also we kept relion-1.4 download from our server because the dependency of opic's code. So, I don't really understand what are discussing here. It is true that we didn't clean the wrappers allowing, in practical terms, that these code can run over Relion-1.4, but you need to add v1.4 to supportedVersions method  to do so. In any case, @azazellochg  feel free to clean up the code. :smile:

**Comment by azazellochg** [comment]
You can go ahead, I will resolve version constants issue if any.

**Comment by azazellochg** [comment]
@delarosatrevin I solved the conflicts, but I cant check if relion-1.x can be downloaded, since scipion install(p/b) in not fully functional for me

**Comment by delarosatrevin** [comment]
Ok, I can't check now (scipion still doesn't run on Mac :( )
But I think we should not worry much about relion-1x binaries...but I will check later anyway. 

Why the install(p/b) is not working?

**Comment by azazellochg** [comment]
@josuegbl  @delarosatrevin Hi guys, could we speed up the review of this PR? 99% of tests failing in buildbot, because most bugs in devel branch are fixed here. In this branch only tests associated with grigoriefflab plugin are failing. Also, I tested the installation of the binaries (see above) and it is fine.

**Comment by delarosatrevin** [comment]
Hi @azazellochg, I will review this PR later today. So, no later than tomorrow it will be merged.

**Pull request merged**
