### PR TITLE
Some improvements to the Relion post-process protocol

### PR DESCRIPTION
**Pull request by delarosatrevin**
In this PR I introduced the following changes to relion-postprocess protocol:
* Parameters in the Form now are in groups, not in different sections (quite empty sections before)
* MTF files listed in the Relion FAQs page are shipped and easy accesible through a 'wizard' for this parameter
* If the input mask is of a different size than the volume, it will be re-scaled in the convertInputStep (as in the 3D auto-refine and classification protocols)

Edit:
Although not specify to post-process, I have added another improvement:
* Create a single link to root folder when no convert or renaming is required.
This will avoid unnecessary links (one per stack, that usually is one per mic/movie). This is quite bad for parallel filesystems since links are entries, so they count the same as a new file. 

I have done some manual tests and also launched the Relion protocol tests...everything seems to be working fine. 

Edit2:
Added small fix about the --pad parameters, it should be used in both normal execution and continue mode. (e.g when you want to skip padding for all but the last iteration)

### CODE REVIEW

**Comment by azazellochg** [comment]
Hi @delarosatrevin I haven't looked at it but did you remove endless prints of symlinks in first step?

**Comment by delarosatrevin** [comment]
Yep, the prints and the links were removed (for the most common case when it is not needed):
https://github.com/scipion-em/scipion-em-relion/pull/55/commits/d159d0146719b0b0aed30b0a922fd81fceb879ad

**Comment by delarosatrevin** [comment]
@azazellochg Have you had any chance to look at this?

**Comment by azazellochg** [comment]
looking now

**Comment by delarosatrevin** [comment]
Tack so mycket!!!

**Pull request merged**
