### PR TITLE
pickers refactoring

### LINKED ISSUE #215: fix picking wizard
```
coordsDir:  Tmp/2.outputMicrographs
java -Xmx2g -Djava.library.path=/home/azazello/soft/scipion3/software/em/xmipp/lib -Dplugins.dir=/home/azazello/soft/scipion3/software/em/xmipp/bindings/java/imagej/plugins -cp lib/*:/home/azazello/soft/scipion3/software/em/xmipp/bindings/java/imagej/*:/home/azazello/soft/scipion3/software/em/xmipp/bindings/java/lib/* xmipp.viewer.particlepicker.training.SupervisedPickerRunner --input Runs/000002_ProtImportMicrographs/micrographs.sqlite --output Tmp/2.outputMicrographs --mode Automatic --classifier Tmp/2.outputMicrographs/picker.conf
Preprocess command: NULL

Autopick command: 
emprogram relion_autopick  --i input_micrographs.star  --pickname autopick --odir "" --LoG --shrink 0 --lowpass 20.000  --LoG_diam_min 260  --LoG_diam_max 360  --LoG_adjust_threshold 0.0 

Autopick output: 
{'PROFILEHOME': '', 'KDE_FULL_SESSION': 'true', 'CONDA_PROMPT_MODIFIER': '(.scipion3env) ', 'LANGUAGE': 'en_US:en', 'USER': 'azazello', 'PAM_KWALLET5_LOGIN': '/run/user/1000/kwallet5.socket', 'XDG_SEAT': 'seat0', 'SSH_AGENT_PID': '1321', 'XDG_SESSION_TYPE': 'x11', 'KONSOLE_VERSION': '200402', 'SHLVL': '1', 'LD_LIBRARY_PATH': '/usr/local/cuda/lib64:/home/azazello/soft/scipion3/software/em/relion-3.1.0/lib:/home/azazello/soft/scipion3/software/em/relion-3.1.0/lib64:/usr/lib64/mpi/gcc/openmpi/lib:/home/azazello/soft/miniconda3/envs/.scipion3env/lib::/home/azazello/soft/scipion3/software/lib:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu/stubs:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/home/azazello/soft/miniconda3/envs/.scipion3env/lib:/home/azazello/soft/scipion3/software/em/xmipp/lib', 'HOME': '/home/azazello', 'OLDPWD': '/home/azazello/soft/scipion3/software/em/xmippSrc-3.20.07b1', 'CONDA_SHLVL': '2', 'DESKTOP_SESSION': '/usr/share/xsessions/plasma', 'SHELL_SESSION_ID': '2e2e695728ba4e269b98137522a4f461', 'GTK_MODULES': 'gail:atk-bridge', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'KDE_SESSION_VERSION': '5', 'KONSOLE_DBUS_SESSION': '/Sessions/4', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'COLORTERM': 'truecolor', 'KONSOLE_DBUS_WINDOW': '/Windows/1', '_CE_M': '', 'SCIPION_TESTS_CMD': 'scipion tests', 'LOGNAME': 'azazello', 'WINDOWID': '4194311', 'QT_AUTO_SCREEN_SCALE_FACTOR': '0', '_': '/home/azazello/soft/scipion3/scipion3', 'XDG_SESSION_CLASS': 'user', 'COLORFGBG': '0;15', 'TERM': 'xterm-256color', 'XDG_SESSION_ID': '8', '_CE_CONDA': '', 'PATH': '/home/azazello/soft/scipion3/software/em/relion-3.1.0/bin:/usr/lib64/mpi/gcc/openmpi/bin:/home/azazello/soft/miniconda3/envs/.scipion3env/bin/python:/home/azazello/soft/miniconda3/envs/.scipion3env/bin:/home/azazello/soft/miniconda3/condabin:/home/azazello/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/cuda/bin:/usr/lib/jvm/java-11-openjdk-amd64/bin:/home/azazello/soft/scipion3/software/em/xmipp/bin', 'SESSION_MANAGER': 'local/debian:@/tmp/.ICE-unix/1375,unix/debian:/tmp/.ICE-unix/1375', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session1', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XCURSOR_THEME': 'breeze_cursors', 'DISPLAY': ':0', 'LANG': 'en_US.UTF-8', 'XDG_CURRENT_DESKTOP': 'KDE', 'CONDA_PREFIX_1': '/home/azazello/soft/miniconda3', 'XDG_SESSION_DESKTOP': 'KDE', 'XAUTHORITY': '/home/azazello/.Xauthority', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'SSH_AUTH_SOCK': '/tmp/ssh-RJzj5e7eInn6/agent.1289', 'CONDA_PYTHON_EXE': '/home/azazello/soft/miniconda3/bin/python', 'SHELL': '/bin/bash', 'QT_ACCESSIBILITY': '1', 'CONDA_DEFAULT_ENV': '.scipion3env', 'KONSOLE_DBUS_SERVICE': ':1.75', 'SCIPION_HOME': '/home/azazello/soft/scipion3', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'XDG_VTNR': '7', 'PWD': '/home/azazello/soft/scipion3/software/em', 'XDG_DATA_DIRS': '/usr/share:/usr/share:/usr/local/share', 'CONDA_EXE': '/home/azazello/soft/miniconda3/bin/conda', 'PYTHONPATH': ':/home/azazello/soft/scipion3/software/bindings:/home/azazello/soft/scipion3/software/em/xmipp/pylib', 'KDE_SESSION_UID': '1000', 'CONDA_PREFIX': '/home/azazello/soft/miniconda3/envs/.scipion3env', 'SCIPION_DOMAIN': 'pwem', 'SCIPION_CONFIG': '/home/azazello/soft/scipion3/config/scipion.conf', 'SCIPION_LOCAL_CONFIG': '/home/azazello/soft/scipion3/config/scipion.conf', 'SCIPION_PROTOCOLS': '/home/azazello/soft/scipion3/config/protocols.conf', 'SCIPION_HOSTS': '/home/azazello/soft/scipion3/config/hosts.conf', 'SCIPION_VERSION': 'v3.0 () devel', 'SCIPION_FONT_NAME': 'Helvetica', 'SCIPION_LOG': '/home/azazello/ScipionUserData/logs/scipion.log', 'SCIPION_LOGO': 'scipion_logo.gif', 'SCIPION_LOGS': '/home/azazello/ScipionUserData/logs', 'SCIPION_NOTES_FILE': 'notes.txt', 'SCIPION_NOTIFY': 'False', 'SCIPION_PLUGIN_REPO_URL': 'http://scipion.i2pc.es/getplugins/', 'SCIPION_SOFTWARE': '/home/azazello/soft/scipion3/software', 'SCIPION_SUPPORT_EMAIL': 'scipion@cnb.csic.es', 'SCIPION_TESTS': '/home/azazello/soft/scipion3/data/tests', 'SCIPION_TESTS_OUTPUT': '/home/azazello/ScipionUserData/Tests', 'SCIPION_TMP': '/home/azazello/ScipionUserData/tmp', 'SCIPION_URL': 'http://scipion.cnb.csic.es/downloads/scipion', 'SCIPION_URL_SOFTWARE': 'http://scipion.cnb.csic.es/downloads/scipion/software', 'SCIPION_URL_TESTDATA': 'http://scipion.cnb.csic.es/downloads/scipion/data/tests', 'SCIPION_USER_DATA': '/home/azazello/ScipionUserData', 'WIZARD_MASK_COLOR': '[0.125, 0.909, 0.972]', 'ASCP': '~/.aspera/connect/bin/ascp', 'ASPERA_SCP_PASS': '', 'ATSAS_HOME': 'software/em/atsas-3.0.1', 'BSOFT_HOME': 'software/em/bsoft-2.0.7', 'CCP4_HOME': 'software/em/ccp4-7.0.056', 'CHIMERA_HEADLESS_HOME': 'software/em/chimera_headless', 'CHIMERA_HOME': 'software/em/chimerax-1.0', 'CISTEM_HOME': 'software/em/cistem-1.0.0-beta', 'CONDA_ACTIVATION_CMD': '. /home/azazello/rc/conda.rc', 'CRYODRGN_ENV_ACTIVATION': 'conda activate cryodrgn-0.2.1', 'CRYOEF_HOME': 'software/em/cryoEF-1.1.0', 'CRYOLO_ENV_ACTIVATION_CPU': 'conda activate cryoloCPU-1.7.2', 'CRYOLO_ENV_ACTIVATION': 'conda activate cryolo-1.7.2', 'CRYOLO_GENERIC_DENOISED_MODEL': 'software/em/cryolo_model-202005_nn_N63_c17/gmodel_phosnet_202005_nn_N63_c17.h5', 'CRYOLO_GENERIC_MODEL': 'software/em/cryolo_model-202005_N63_c17/gmodel_phosnet_202005_N63_c17.h5', 'CRYOLO_NS_GENERIC_MODEL': 'software/em/cryolo_negstain_model-20190226/gmodel_phosnet_negstain_20190226.h5', 'CRYO_PROJECTS_DIR': 'scipion_projects', 'CRYOSPARC_HOME': 'software/em/cryosparc-v2.15.0', 'CRYOSPARC_USER': 'azazello', 'CTFFIND4_HOME': 'software/em/ctffind4-4.1.13', 'DOGPICKER_HOME': 'software/em/dogpicker-0.2.1.1', 'EMAN2_HOME': 'software/em/eman-2.31', 'EMFACILITIES_HOME': '~/.config/scipion', 'EMPIAR_TOKEN': '', 'EM_ROOT': 'software/em', 'EMXLIB_HOME': 'software/em/emx_export-1.0.0', 'ETHAN_HOME': 'software/em/ethan-1.2', 'FSC3D_ACTIVATION_CMD': 'conda activate 3DFSC', 'FSC3D_HOME': 'software/em/fsc3D-3.0', 'GAUTOMATCH': 'Gautomatch_v0.56_sm30-75_cu10.1', 'GAUTOMATCH_HOME': 'software/em/gautomatch-0.56', 'GCTF': 'Gctf_v1.18_sm30-75_cu10.1', 'GCTF_HOME': 'software/em/gctf-1.18', 'IMAGIC_HOME': 'software/em/imagic-180311', 'IMOD_HOME': 'software/em/imod-4.10.42', 'JANNI_GENERIC_MODEL': 'software/em/janni_model-20190703/gmodel_janni_20190703.h5', 'LOCSCALE_HOME': 'software/em/locscale-0.1', 'MAXIT_HOME': 'software/em/maxit-10.1', 'MOTIONCOR2_BIN': 'MotionCor2_1.3.2-Cuda101', 'MOTIONCOR2_CUDA_LIB': '/usr/local/cuda/lib64', 'MOTIONCOR2_HOME': 'software/em/motioncor2-1.3.2', 'NOVACTF_HOME': 'software/em/novactf-master', 'PHENIX_HOME': 'software/em/phenix-1.17', 'RELION_HOME': 'software/em/relion-3.1.0', 'RESMAP_GPU_LIB': 'ResMap_krnl-cuda-V10.1.105-sm35_gpu.so', 'RESMAP_HOME': 'software/em/resmap-1.95', 'RESMAP': 'ResMap-1.95-cuda-Centos7x64', 'SIDESPLITTER_HOME': 'software/em/sidesplitter-1.0', 'SPIDER_HOME': 'software/em/spider-26.06', 'SPIDER_MPI': 'spider_linux_mpi_opt64', 'SPIDER': 'spider_linux_mp_intel64', 'TOPAZ_ENV_ACTIVATION': 'conda activate topaz-0.2.3', 'VIEWERS': '{"Volume":["pwem.viewers.viewers_data.DataViewer"]}', 'XMIPP_HOME': '/home/azazello/soft/scipion3/software/em/xmipp', 'SCIPION_CWD': '/home/azazello/soft/scipion3/software/em', 'SCIPION_DEBUG': '1', 'SCIPION_DEBUG_NOCLEAN': 'True', 'CUDA': 'True', 'CHIMERA_LAUNCHER': '/home/azazello/soft/scipion3/software/em/chimerax-1.0/bin/ChimeraX %s', 'GDK_BACKEND': 'x11'} + Run autopicking on the following micrographs: 
    * mic_000001.mrc
    * mic_000002.mrc
    * mic_000003.mrc
    * mic_000004.mrc
    * mic_000005.mrc
    * mic_000006.mrc
    * mic_000007.mrc
    * mic_000008.mrc
    * mic_000009.mrc
    * mic_000010.mrc
    * mic_000011.mrc
    * mic_000012.mrc
    * mic_000013.mrc
    * mic_000014.mrc
    * mic_000015.mrc
    * mic_000016.mrc
    * mic_000017.mrc
    * mic_000018.mrc
    * mic_000019.mrc
    * mic_000020.mrc
 + Will use following diameters for Laplacian-of-Gaussian filter: 
   * 52 (too low)
   * 65 (too low)
   * 87 (too low)
   * 130 (too low)
   * 260 (ok)
   * 310 (ok)
   * 360 (ok)
   * 720 (too high)
   * 1080 (too high)
   * 1440 (too high)
   * 1800 (too high)
 + WARNING: Requested rescale of micrographs is 724 pixels. The largest prime factor in FFTs is 181
 + WARNING: Will change rescaling of micrographs to 726 pixels, because the prime factor then becomes 13
 + WARNING: add --skip_optimise_scale to your autopick command to prevent rescaling 
 Autopicking ...
000/??? sec ~~(,_,">                                                          [oo]
   0/   0 sec ...~~(,_,">
   0/   0 sec ......~~(,_,">
   1/   6 sec ........~~(,_,">
   1/   5 sec ...........~~(,_,">
   1/   4 sec ...............~~(,_,">
   1/   3 sec ..................~~(,_,">
   1/   2 sec .....................~~(,_,">
   2/   5 sec .......................~~(,_,">
   2/   4 sec ...........................~~(,_,">
   2/   4 sec ..............................~~(,_,">
   2/   3 sec .................................~~(,_,">
   2/   3 sec ....................................~~(,_,">
   3/   4 sec .......................................~~(,_,">
   3/   4 sec ..........................................~~(,_,">
   3/   4 sec .............................................~~(,_,">
   3/   3 sec ................................................~~(,_,">
   3/   3 sec ...................................................~~(,_,">
   4/   4 sec ......................................................~~(,_,">
   4/   4 sec .........................................................~~(,_,">
   4/   4 sec ............................................................~~(,_,">
 Generating logfile.pdf ... 
000/??? sec ~~(,_,">                                                          [oo]
   0/   0 sec ............................................................~~(,_,">
 Total number of particles from 20 micrographs is 7130
 i.e. on average there were 357 particles per micrograph
 Done! Written: logfile.pdf 

** Running command: relion_autopick "--i" "input_micrographs.star" "--pickname" "autopick" "--odir" """" "--LoG" "--shrink" "0" "--lowpass" "20.000" "--LoG_diam_min" "260" "--LoG_diam_max" "360" "--LoG_adjust_threshold" "0.0"


Convert command: 
emconvert --coordinates --from relion --to xmipp --input Runs/000002_ProtImportMicrographs/micrographs.sqlite --output Tmp/2.outputMicrographs --extra Tmp/2.outputMicrographs/

Convert output: 
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/006_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/006_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/008_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/008_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/016_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/016_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/019_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/019_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/060_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/060_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/066_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/066_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/068_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/068_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/069_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/069_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/071_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/071_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/101_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/101_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/106_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/106_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/112_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/112_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/116_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/116_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/124_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/124_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/128_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/128_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/129_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/129_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/136_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/136_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/142_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/142_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/151_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/151_autopick.star
WARNING: Missing coordinates star file:  Tmp/2.outputMicrographs/165_autopick.star
WARNING: Error reading coordinates star file:  Tmp/2.outputMicrographs/165_autopick.star
writeCoordsConfig: state= Automatic
/bin/bash: /home/azazello/soft/miniconda3/envs/.scipion3env/lib/libtinfo.so.6: no version information available (required by /bin/bash)

```

### PR DESCRIPTION
**Pull request by azazellochg**
- remove ref picker wizard
- remove optimize mode for refpicker
- fix logpicker wizard (close #215)
- fix --odir param

Optimize mode, imho, is not very useful since autopicking on a few mics is very fast (both Log/Ref pickers) without any complicated code dealing with the FOM maps.

### CODE REVIEW

**Comment by azazellochg** [comment]
Streaming works. Also, opening old projects works, just a harmless warning:
micrographsSubset attribute is not defined as parameter. This could happen when loading new code with older scipion versions.

**Review by delarosatrevin — CHANGES_REQUESTED** [review]
Nice clean up!

Wizard for LOG picker does not seem to be working. I would propose to completely remove the wizard. We can run the protocol with few CPU and small batch sizes, so results should appear quickly.

**Comment by delarosatrevin** [comment]
I can help with testing ;)

**Review by delarosatrevin — APPROVED** [review]
Working as expected.

**Pull request merged**
