### PR TITLE
Parallel micrograph processing

### PR DESCRIPTION
**Pull request by DaniDelHoyo**
Allows the parallel processing of micrographs.
Solves https://github.com/scipion-em/scipion-em/issues/162

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@DaniDelHoyo Solving this issue is not as simple as changing this property. 
When you have parallel steps, you can use either MPI or threads to run steps in parallel, but not both. So, it will be very inefficient to process it one by one here (with a single core), even if in parallel. With the current approach, the threads are used to process one movie as fast as possible, which reduces the IO overhead in the parallel variant. 

We will implement a more efficient approach in the near future that also includes batches and could make use of parallel setup and available cores to work in one or many items at once. So, I'm very sorry but I'm rejecting your PR for now, thanks anyway for looking into this.

**Comment by pconesa** [comment]
Thanks @DaniDelHoyo .

I thought it was going to fix it too, but I see there are more implications.

I'm transferring the issue related here and assigning it to you. Hope you agree.

**Comment by DaniDelHoyo** [comment]
@delarosatrevin in the few tests I have performed, the protocol runs notably faster using several threads, but I agree that it can be further optimized and your approach sounds much better. I just found this very simple change useful, but I am glad that this issue is not abandoned.
Good luck and best regards,
Dani

**Comment by delarosatrevin** [comment]
Thanks again @DaniDelHoyo. I will keep you posted about this.

**Pull request closed without merging**
