### PR TITLE
3.1.2

### LINKED ISSUE #294: Import particles not storing the acquisition info properly.
**Describe the bug**
When importing a start file in the import particles protocol ("relion" mode) the acquisition is not stored properly

**To Reproduce**
Steps to reproduce the behaviour:
1. Add import particles protocol
2. choose option "relion"
3. chose a star file from relion3.1 (we have tested using one from the dataset: data/tests/relion31_tutorial_precalculated/Class2D/job013/run_it025_data.star)
4. Acquisition object is not populated, not at set level nor at item level 

**Desktop (please complete the following information):**
 - Scipion version: [devel branches]
 - Relion plugin version [ branch [devel]

**Additional context**
Wizard gets the values right.

Here, Acquisition is populated correctly (we printed it) https://github.com/scipion-em/scipion-em-relion/blob/master/relion/convert/dataimport.py#L102

Here, Acquisition is overwritten --> https://github.com/scipion-em/scipion-em-relion/blob/c116c9f3c1ece66e6c62118f34aeecc2da2a0187/relion/convert/convert31.py#L545

image

### PR DESCRIPTION
**Pull request by azazellochg**
- Allow to use Environ.setPrepend (depend on scipion-em/scipion-pyworkflow#238) to set different prepend commands (e.g when optimized CPU module is available)
- fixes for subtract no relion protocol
- fix #294, #296

### CODE REVIEW

**Comment by azazellochg** [comment]
@delarosatrevin you might want to add notes to README about how to use prepend. 
Also, this PR needs to be delayed as prepend only works for the latest core release.

**Comment by delarosatrevin** [comment]
Hi @azazellochg 
Yes, I will update the README about the PREPEND var. And also yes, we need to way to the release of the pyworkflow.

**Comment by azazellochg** [comment]
the core update is released but I prefere to wait otherwise there'll be emails from users with not latest pw version

**Comment by delarosatrevin** [comment]
Ah, right! Anyway is very. likely that if they update the plugin. will also
update the core. Another option is to make it work even. with the previous
version...but not sure if worth the effort.

**Pull request merged**
