### PR TITLE
release 1.0.9

### PR DESCRIPTION
**Pull request by azazellochg**
Fixing multibody bug

### CODE REVIEW

**Comment by azazellochg** [comment]
@delarosatrevin Pablo will update a few files in the test data and then it should run ok.

**Comment by azazellochg** [comment]
Closes #121

**Comment by azazellochg** [comment]
I'll run the final test overnight and then merge

**Comment by delarosatrevin** [comment]
Please don't merge yet, I will like to address issue #122 for this release.

**Comment by azazellochg** [comment]
My test has failed, so I have to investigate

**Comment by azazellochg** [comment]
I'm done, @delarosatrevin . :)

**Comment by delarosatrevin** [comment]
@azazellochg  Issue #122 is not going to be addressed here, so we can move on.

**Comment by azazellochg** [comment]
@delarosatrevin you can publish the release, just don't forget to push changes to py3/r3.1

**Comment by azazellochg** [comment]
This also fixes #140

**Pull request merged**
