### PR TITLE
Update CTF and OpticsGroup after ctf-refinement 

### PR DESCRIPTION
**Pull request by delarosatrevin**
Now the CTF-refinment protocol should run with both Relion 3.0 and 3.1
It does finish with Betagal tutorial but we need to check if there are changes in CTF (I saw same input values)

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@azazellochg Can you also check about new (or different) parameters in 3.1? Just to double-check we are not missing something.

**Comment by azazellochg** [comment]
Hi @delarosatrevin . Parameters are ok.
1) expandsymmetry test now fails (discovered by chance)
```
>>> ERROR running protocol relion - expand symmetry
    FAILED with error: Protocol failed: 'dict_values' object is not subscriptable

  2020-06-11 12:04:44.714094
Traceback (most recent call last):
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
    self._run()
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
    resultFiles = self._runFunc()
  File "/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
    return self._func(*self._args)
  File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-relion/relion/protocols/protocol_expand_symmetry.py", line 95, in createOutputStep
    convert.readSetOfParticles(
  File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-relion/relion/convert/__init__.py", line 98, in readSetOfParticles
    return createReader(**kwargs).readSetOfParticles(starFile, partsSet, **kwargs)
  File "/lmb/home/gsharov/soft/scipion-em-plugins/scipion-em-relion/relion/convert/convert31.py", line 353, in readSetOfParticles
    self._pixelSize = getattr(self._optics.values()[0],
TypeError: 'dict_values' object is not subscriptable
Protocol failed: 'dict_values' object is not subscriptable
FAILED: createOutputStep, step 3
```
2) this PR does not fix the underlying issue of acquisition dict. The way it should work is e.g. I ran ctf refinement with only mag correction -> got new columns in optics table. Then I run ctf refinement with beam tilt correction, using previous output as input. Now none of optics table parameters are saved in acquisition dict, so upon convertinput step I get no information about mag distortions in the star file.

**Comment by azazellochg** [comment]
I'll merge it so buildbot can start testing it, then I'll check the errors if any. Thank you, @delarosatrevin

**Comment by delarosatrevin** [comment]
Ok, I will continue testing on devel and create a new branch if many changes are required.

**Pull request merged**
