### PR TITLE
progressbar added to clasiffy_3D

### PR DESCRIPTION
**Pull request by rmarabini**
Hi,

   I am working with more than one million particles and the conversion from scipion metadata to relion star files takes a while (from 10 minutes to 1 hour depending on the machine and how busy is the system). During this time the user does not get any feedback. I would suggest to create a progress-bar  to keep users -include myself- entertained. 

  In this pull request I have created a Progressbar class (file progressbar.py) that is called in the convert.py routine setOfImagesToMd. The output appears in stdout tab in scipion GUI.

 Python have a module called progressbar that may also been used to implement toolbars but I think the proposed class is a better solution since we may modify it as we please and it has less overhead.

Please have a look to the pull request. If you like it we may move the progress bar to scipion code and make it available to other packages.

---

P.S: One intriguing behavior of the progressbar that I do not understand is that if a print something from the progressbar file the output goes to the terminal while if I do the same from the convert file the output goes to the stdout tab in Scipion GUI.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@rmarabini I understand the problem...but I have some concerns:
* First, the ProgressBar should be implemented in the Scipion core (i.e pyworkflow) not in the Relion plugin
* Second, if you are working with 1million particles...in the sake of entertaining...you have added 2 million operations (one % and one ==). Every small bit of code counts when we are talking about millions of iterations in a loop. So you have made the conversion slower  :(

Regarding the intriguing behavior, if you print something in the protocol steps code, it will be redirected into a file...this does not happens if it is in a wizard, or another part of the code.

**Comment by rmarabini** [comment]
On Mon, Jun 24, 2019 at 11:02 AM Jose Miguel de la Rosa Trevin <
notifications@github.com> wrote:

> @rmarabini <https://github.com/rmarabini> I understand the problem...but
> I have some concerns:
>
>    - First, the ProgressBar should be implemented in the Scipion core
>    (i.e pyworkflow) not in the Relion plugin
>
> I do agree with that

>
>    - Second, if you are working with 1million particles...in the sake of
>    entertaining...you have added 2 million operations (one % and one ==).
>    Every small bit of code counts when we are talking about millions of
>    iterations in a loop. So you have made the conversion slower :(
>
>
the overhead is 0.0902440547943 sec in my computer for

import time

i = time.time()
for i in range(1000000):
    if i%10000 == 0:
          print ".",


t = time.time()
print ii-t



>
> Regarding the intriguing behavior, if you print something in the protocol
> steps code, it will be redirected into a file...this does not happens if it
> is in a wizard, or another part of the code.
>

Still I do not understand this.  protocol_relion_classify3D is a protocol
which calls a function in convert (setOfImagesToMd). Anything printed
in setOfImagesToMd
goes to the stdout tab in scipion GUI but if setOfImagesToMd calls to
progressbar and progressbar prints something
it goes to the terminal. why convert is part of the protocol but
progressbar is not?

The natural place to print the progress bar would be from the progressbar
class but I do not know how to do that and get the output in the scipion
tab.

**Comment by azazellochg** [comment]
there is nothing left in scipion to improve except entertainment? I will not merge this

**Comment by delarosatrevin** [comment]
I'm with @azazellochg in this, @rmarabini . As I said, I like the progressbar idea, but we can wait until it is implemented in pyworkflow.  Moreover,  there are many other issues to be addresses both in Scipion and the plugin with higher priority than this.

**Comment by rmarabini** [comment]
OK @azazellochg  and @delarosatrevin , I just opened the corresponding pull request in scipion in order to incorporate the progressbar. If approved I  think that it will be a good idea to incorporate it to the convert routine in relion plugin and, in this way, provide feedback to users. Otherwise, when the number of particles is large what  users perceive is that scipion spends a long time in the step 0 doing nothing. (This is also true in many other plugins)

The overhead (I measured it) is negligible and while it is true that many issues need to be addressed in relion with higher priority I fail to see why this one cannot be addressed if the code is already available and the cost to incorporate it , check that it works, is very little.

Nevertheless, the last word is yours.

**Pull request closed without merging**
