### PR TITLE
Jj tomo

### PR DESCRIPTION
**Pull request by azazellochg**
`Hi, @azazellochg and @delarosatrevin,

This branch contains some protocols developed for tomography in Relion, working from the old ones started by Josue.
They are independent from the SPA files and could be in a separate folder if you consider it to be the best option.
It is remarkable that they has a new dependency on the requirements, which is scipion-em-tomo for the tomo objects and it is completely up-to-date with devel, but it's for Relion 3.0. Even though, I think it should be easy to adapt them to Relion 3.1.
Image processing users in B13 have been using them with real data during last weeks and the protocols seem to be working nicely.

Kind regards.`

### CODE REVIEW

**Comment by azazellochg** [comment]
@JorMaister this will not be merged any time soon (before scipion 3 is released) as I do not accept any new code until a stable plugin is released.

**Comment by azazellochg** [comment]
Also, as time passes, 3.0 support will be removed, so it's up to you to port it to 3.1+.

**Comment by pconesa** [comment]
Hi @azazellochg , I understand your concerns. But I'd also try to review the code. @JorMaister has made a huge effort to keep tomo code isolated minimizing the impact of this PR. I think there is no way to destabilize the plugin with this code. There are only file additions and only modifications are at:

convert/__init__.py : 2 new methods (this can't break anything)
protocols.conf: adding a the tomography view
protocols/__init__py : neccesary imports
setup.py: scipion-em-tomo 

Obviously, the introduced code may have a bug. I mean, tomo protocols might fail under untested scenarios for sure. But I fail to see how this new code can break any previous existing code. There is 0 overlap.

Additionally, we are aiming to release tomo plugins (quite stable now) with scipion3. It would be nice to have this changes too.

Maybe, if you insist in your position.....we could release relion tomo plugin...maybe will help to keep thing small and manageable?

@JorMaister, maybe this is not as easy I see it, or maybe it is?

**Comment by JorMaister** [comment]
Hi @pconesa, @azazellochg ,
It should be easy to move it to a relion-tomo plugin since there's no code overlapping. We would also assume the maintenance of that code. What are your thoughts about this option, @azazellochg?

**Comment by delarosatrevin** [comment]
@pconesa Independently of code overlap, I agree with @azazellochg that we should not merge new code, that introduced other dependencies and introduces protocols that are not completely tested. I think it is a matter of branch names and development workflow. We will prefer to focus on the current release and not having a separate branch that diverges too much. If you. want to use this. code, you could still call it devel-tomo or something like this. We are still using devel for changes that will go into the stable release supporting Relion 3.1. 

@pconesa Do you really believe tomo plugins are quite stable now? Do you know how much time took to stabilize SPA protocols/plugins?  Are these tomo plugins/protocols really tested (outside CNB) ???

@JorMaister I strongly opposed to creating a separate plugin for this...we don't have xmipp-tomo,  eman-tomo and so on. And I also envision a  lot of duplication and out-of-sync code.  Still, the nice thing with the plugins that anyone is free to create any plugin they like.

**Comment by pconesa** [comment]
Ok, we are going to create a relion-tomo plugin. There is already a xmipp-tomo plugin (@delarosatrevin ).

There will not be code duplication. Basically the code of this branch will be extracted taken to the new plugin....and the rest of the functionality will be taken from this plugin. I think this way we cover everyone needs.

Tomography workflow has not been tested outside CNB is true, but inside is working and is coming toghether. I do not see ant problem in releasing tomo, and in case we consider it releasing it with all caution and tagging things as "beta".

**Pull request closed without merging**
