### PR TITLE
save  beamtilt

### PR DESCRIPTION
**Pull request by rmarabini**
This pull request has two purposes

   1) save beamtiltX and beamtiltY parameters in setOfParticles
   2) relion_reconstruct  is called (in relion3 version) as  relion_reconstruct_openmp. In my version of relion3 the correct name is relion_reconstruct (no openmp) and I can not see any flag that will create the openmp version.

### CODE REVIEW

**Comment by delarosatrevin** [comment]
@rmarabini I think you should have Relion compiled with OpenMP support, so this is something about your installation. Maybe we need to find out a general solution to be more robust to this case.

**Comment by delarosatrevin** [comment]
Hum... @rmarabini PRs should be reviewed by other person before merging.

**Comment by rmarabini** [comment]
> @rmarabini I think you should have Relion compiled with OpenMP support, so this is something about your installation. Maybe we need to find out a general solution to be more robust to this case.

Hi @delarosatrevin,

   About opempi, In my machine the libraries are detected by cmake and I guess they are used in compilation time but I have no idea if this is the case. What I know is that the output binary is called relion_reconstruct  (no relion_reconstruct_openmp) and that the README does not comment on any openmp flag that needs to be supplied. 

   How did you compile your code in order to produce the relion_reconstruct_openmp binary?

**Comment by delarosatrevin** [comment]
It is not OpenMPI, it is OpenMP, an alternative library for threading (instead of pthreads).

**Comment by rmarabini** [comment]
@delarosa Did I merge it? My intention was to create a pull request. I will
undo de commit and create a pull request

**Comment by delarosatrevin** [comment]
Here you can find it in the cmake: 
https://github.com/3dem/relion/blob/600499f35c721e2009135ee027078e69414f7edb/src/apps/CMakeLists.txt#L219

**Comment by delarosatrevin** [comment]
Not need to undo the commits, I think we can still look a the differences and work in the relion3 branch, that is in a PR already...but it is better to see the changes isolated. Anyway, I think we can see the differences in github and comment, despite the PR was merged. 
PS: Remember, if you drink, don't use git :P

**Comment by rmarabini** [comment]
Uhm,

    cmake detect openmp and print the corresponding mesasge OPENMP FOUND
but the created binary file does not
has the suffix openmp

**Pull request merged**
